name: Build GKI Kernel with MemKernel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-gki-kernel:
    name: Build GKI Kernel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Kernel Environment
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            libncurses-dev \
            bison \
            flex \
            libssl-dev \
            bc \
            ccache \
            gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi \
            curl

      - name: Clone GKI Kernel Source
        run: |
          git clone https://android.googlesource.com/kernel/common -b android-12-5.10 kernel_src
          cd kernel_src
          git checkout 5.10.198-android12-9

      - name: Integrate MemKernel Driver
        run: |
          cd kernel_src
          curl -LSs "https://raw.githubusercontent.com/Poko-Apps/MemKernel/main/kernel/setup.sh" | bash -s Y

      - name: Configure Kernel
        run: |
          cd kernel_src
          make ARCH=arm64 defconfig
          make ARCH=arm64 menuconfig

      - name: Build Kernel
        run: |
          cd kernel_src
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gki-kernel-build
          path: kernel_src/arch/arm64/boot/
